2024-10-02 18:24:58,147 -|- WARNING -|- Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\NoName\PycharmProjects\Urban\Module12\tests_12_4.py", line 25, in test_run
    r2 = Runner(5)
         ^^^^^^^^^
  File "C:\Users\NoName\PycharmProjects\Urban\Module12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только числом, передано {type(name).__name__}')
TypeError: Имя может быть только числом, передано int
2024-10-02 18:24:58,148 -|- WARNING -|- Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\NoName\PycharmProjects\Urban\Module12\tests_12_4.py", line 15, in test_walk
    r1 = Runner('Bully', -5)
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\NoName\PycharmProjects\Urban\Module12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
